FROM mcr.microsoft.com/dotnet/framework/sdk:4.8

WORKDIR /app/

VOLUME C:\\app\\FaunaDB.Client\\bin\\Release

ADD . /app/

COPY "Scripts/0-build-pack.ps1" /app/entrypoint.ps1

ENTRYPOINT [ "powershell.exe", "/app/entrypoint.ps1" ]
