version: 2.1
description: FaunaDB C# Driver Tests

executors:
  core:
    parameters:
      version:
        type: enum
        enum: ["stable", "nightly"]
    resource_class: large
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

      - image: gcr.io/faunadb-cloud/faunadb/enterprise/<<parameters.version>>:latest
        name: core
        auth:
          username: _json_key
          password: $GCR_KEY

    environment:
      FAUNA_ROOT_KEY: secret
      FAUNA_DOMAIN: core
      FAUNA_SCHEME: http
      FAUNA_PORT: 8443
      FAUNA_TIMEOUT: 60s

commands:
  build_and_test:
    description: "Run C# tests"
    steps:
      - checkout

      - run:
          name: Wait FaunaDB init
          command: |
            while ! $(curl --output /dev/null --silent --fail --max-time 1 http://core:8443/ping); do sleep 1; done

      - run:
          name: Run Tests 3.1
          command: |
            dotnet --info
            mkdir results31
            dotnet restore
            dotnet test --framework netcoreapp3.1 --logger "junit;LogFilePath=./results/results31.xml" FaunaDB.Client.Test
      
      - run:
          name: Run Tests 5.0
          command: |
            wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
            dpkg -i packages-microsoft-prod.deb
            rm packages-microsoft-prod.deb
            apt-get update; \
            apt-get install -y apt-transport-https && \
            apt-get update && \
            apt-get install -y dotnet-sdk-5.0
            dotnet --info
            mkdir results50
            dotnet restore
            dotnet test --framework net5.0 --logger "junit;LogFilePath=./results/results50.xml" FaunaDB.Client.Test
            
      - run:
          name: Run Tests 45
          command: |
            apt update
            apt install dirmngr gnupg apt-transport-https ca-certificates
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
            sh -c 'echo "deb https://download.mono-project.com/repo/debian stable-buster main" > /etc/apt/sources.list.d/mono-official-stable.list'
            apt update
            apt-get -y install mono-complete
            mono --version
            dotnet --info
            mkdir results45
            dotnet restore
            dotnet test --framework net47 FaunaDB.Client.Test
            dotnet test --framework net46 FaunaDB.Client.Test
            dotnet test --framework net45 FaunaDB.Client.Test
            
      - store_test_results:
          path: FaunaDB.Client.Test/results/

jobs:
  core-stable:
    executor:
      name: core
      version: stable
    steps:
      - build_and_test

  core-nightly:
    executor:
      name: core
      version: nightly
    steps:
      - build_and_test

workflows:
  version: 2
  build_and_test:
    jobs:
      - core-stable:
          context: faunadb-drivers
      - core-nightly:
          context: faunadb-drivers
