version: 2.1
description: FaunaDB C# Driver Tests
jobs:
  build:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: xcodebuild -version
      - run:
          name: Install Dotnet
          command: |
            curl https://download.visualstudio.microsoft.com/download/pr/5b8d25c1-85e1-4b18-8d96-b14115586319/78ff638656c3a90324e810f8dd157422/dotnet-sdk-2.2.207-osx-x64.tar.gz --output install.tar.gz 
            mkdir install-dotnet/
            cd install-dotnet
            tar -xzvf ../install.tar.gz
            ./dotnet --version
            cd ../
      - run:
          name: Run Tests
          command: |
            mkdir -p results/junit
            ./install-dotnet/dotnet restore
            ./install-dotnet/dotnet test --framework netcoreapp2.0 --logger "junit;LogFilePath=./results/junit/results.xml" FaunaDB.Client.Test
      - store_test_results:
          path: FaunaDB.Client.Test/results/
