.TH "/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/obj/Release/netstandard2.0/.NETStandard,Version=v2.0.AssemblyAttributes.cs" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/obj/Release/netstandard2.0/.NETStandard,Version=v2.0.AssemblyAttributes.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
