.TH "/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Utils Directory Reference" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Utils Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCheckLatestVersion\&.cs\fP"
.br
.ti -1c
.RI "file \fBDateTimeExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBHashUtil\&.cs\fP"
.br
.in -1c
