.TH "/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/obj/Debug/netstandard2.1 Directory Reference" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/obj/Debug/netstandard2.1 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.NETStandard,Version=v2\&.1\&.AssemblyAttributes\&.cs\fP"
.br
.ti -1c
.RI "file \fBFaunaDB\&.Client\&.AssemblyInfo\&.cs\fP"
.br
.in -1c
