.TH "/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client Directory Reference" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBClient\fP"
.br
.ti -1c
.RI "directory \fBCollections\fP"
.br
.ti -1c
.RI "directory \fBErrors\fP"
.br
.ti -1c
.RI "directory \fBobj\fP"
.br
.ti -1c
.RI "directory \fBProperties\fP"
.br
.ti -1c
.RI "directory \fBQuery\fP"
.br
.ti -1c
.RI "directory \fBTypes\fP"
.br
.ti -1c
.RI "directory \fBUtils\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGlobalSuppressions\&.cs\fP"
.br
.in -1c
