.TH "/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Utils/CheckLatestVersion.cs" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Utils/CheckLatestVersion.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFaunaDB\&.Client\&.Utils\&.CheckLatestVersion\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFaunaDB\fP"
.br
.ti -1c
.RI "namespace \fBFaunaDB\&.Client\fP"
.br
.RI "A thread-safe static helper used to store the last seen transaction time returned by the database\&. "
.ti -1c
.RI "namespace \fBFaunaDB\&.Client\&.Utils\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
