.TH "/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Types/Decoder.cs" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Types/Decoder.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.Decoder\fP"
.br
.RI "\fBFaunaDB\fP \fBValue\fP to object decoder\&. "
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.DecoderImpl\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFaunaDB\fP"
.br
.ti -1c
.RI "namespace \fBFaunaDB\&.Types\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBConverter\fP = System\&.Func< \fBFaunaDB\&.Types\&.Value\fP, object >"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBConverter\fP =  System\&.Func<\fBFaunaDB\&.Types\&.Value\fP, object>"

.PP
Definition at line 9 of file Decoder\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
