.TH "/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Types/Encoder.cs" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Types/Encoder.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.Encoder\fP"
.br
.RI "\fBFaunaDB\fP object to \fBValue\fP encoder\&. "
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.EncoderImpl\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFaunaDB\fP"
.br
.ti -1c
.RI "namespace \fBFaunaDB\&.Types\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBConverter\fP = System\&.Func< FaunaDB\&.Types\&.EncoderImpl, object, \fBFaunaDB\&.Types\&.Value\fP >"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBConverter\fP =  System\&.Func<FaunaDB\&.Types\&.EncoderImpl, object, \fBFaunaDB\&.Types\&.Value\fP>"

.PP
Definition at line 10 of file Encoder\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
