.TH "FaunaDB.Query.Language.LetBinding" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Query.Language.LetBinding
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpr\fP \fBIn\fP (\fBExpr\fP @in)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file Language\&.Basic\&.Let\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBExpr\fP FaunaDB\&.Query\&.Language\&.LetBinding\&.In (\fBExpr\fP @ in)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
