.TH "FaunaDB.Errors.Unauthorized" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Errors.Unauthorized \- HTTP 401 error\&. An exception thrown if \fBFaunaDB\fP responds with an HTTP 401 (\fBUnauthorized\fP)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFaunaDB\&.Errors\&.FaunaException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
HTTP 401 error\&. An exception thrown if \fBFaunaDB\fP responds with an HTTP 401 (\fBUnauthorized\fP)\&. 

HTTP 401 error\&.
.PP
Definition at line 51 of file FaunaException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
