.TH "FaunaDB.Query.Language.Cursor" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Query.Language.Cursor \- Creates a new \fBCursor\fP to be used with a Paginate expression\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBExpr\fP \fBSource\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Creates a new \fBCursor\fP to be used with a Paginate expression\&. 

See the \fBFaunaDB\fP Paginate Function
.PP
Definition at line 60 of file Language\&.Read\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBExpr\fP FaunaDB\&.Query\&.Language\&.Cursor\&.Source\fC [get]\fP"

.PP
Definition at line 62 of file Language\&.Read\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
