.TH "FaunaDB.Types.DoubleV" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Types.DoubleV \- Represents a Double value in the \fBFaunaDB\fP query language\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFaunaDB\&.Types\&.ScalarValue< double >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDoubleV\fP \fBOf\fP (double v)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Represents a Double value in the \fBFaunaDB\fP query language\&. 


.PP
Definition at line 60 of file ScalarValue\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBDoubleV\fP FaunaDB\&.Types\&.DoubleV\&.Of (double v)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
