.TH "FaunaDB.Types.ExprV" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Types.ExprV \- A \fBFaunaDB\fP Expression wrapped as a \fBValue\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFaunaDB\&.Types\&.ScalarValue< Expr >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBFaunaDB\fP Expression wrapped as a \fBValue\fP 


.PP
Definition at line 128 of file ScalarValue\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
