.TH "FaunaDB.Types.ScalarValue< TWrapped >" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Types.ScalarValue< TWrapped > \- Represents a scalar value at the \fBFaunaDB\fP query language\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFaunaDB\&.Types\&.Value\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBEquals\fP (\fBExpr\fP v)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBScalarValue\fP (TWrapped value)"
.br
.ti -1c
.RI "override int \fBHashCode\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TWrapped \fBValue\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Represents a scalar value at the \fBFaunaDB\fP query language\&. 


.PP
Definition at line 14 of file ScalarValue\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBFaunaDB\&.Types\&.ScalarValue\fP< TWrapped >\&.\fBScalarValue\fP (TWrapped value)\fC [protected]\fP"

.PP
Definition at line 18 of file ScalarValue\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool \fBFaunaDB\&.Types\&.ScalarValue\fP< TWrapped >\&.Equals (\fBExpr\fP v)\fC [virtual]\fP"

.PP
Implements \fBFaunaDB\&.Query\&.Expr\fP\&.
.PP
Definition at line 29 of file ScalarValue\&.cs\&.
.SS "override int \fBFaunaDB\&.Types\&.ScalarValue\fP< TWrapped >\&.HashCode ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBFaunaDB\&.Query\&.Expr\fP\&.
.SS "override string \fBFaunaDB\&.Types\&.ScalarValue\fP< TWrapped >\&.ToString ()"

.SH "Property Documentation"
.PP 
.SS "TWrapped \fBFaunaDB\&.Types\&.ScalarValue\fP< TWrapped >\&.\fBValue\fP\fC [get]\fP"

.PP
Definition at line 16 of file ScalarValue\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
