.TH "FaunaDB.Types.DefaultNamingStrategy" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Types.DefaultNamingStrategy
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFaunaDB\&.Types\&.NamingStrategy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBResolvePropertyName\fP (string name)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file NamingStrategy\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override string FaunaDB\&.Types\&.DefaultNamingStrategy\&.ResolvePropertyName (string name)\fC [virtual]\fP"

.PP
Implements \fBFaunaDB\&.Types\&.NamingStrategy\fP\&.
.PP
Definition at line 17 of file NamingStrategy\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
