.TH "FaunaDB.Errors.UnknowException" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Errors.UnknowException \- An exception thrown if a \fBFaunaDB\fP response is unknown or unparseable by the client\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFaunaDB\&.Errors\&.FaunaException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An exception thrown if a \fBFaunaDB\fP response is unknown or unparseable by the client\&. 


.PP
Definition at line 115 of file FaunaException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
