.TH "FaunaDB.Types.StringV" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Types.StringV \- Represents a String value in the \fBFaunaDB\fP query language\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFaunaDB\&.Types\&.ScalarValue< string >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBStringV\fP \fBOf\fP (string v)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Represents a String value in the \fBFaunaDB\fP query language\&. 


.PP
Definition at line 82 of file ScalarValue\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBStringV\fP FaunaDB\&.Types\&.StringV\&.Of (string v)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
