.TH "FaunaDB.Errors.QueryError" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Errors.QueryError
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQueryError\fP (IReadOnlyList< string > position, string code, string description, IReadOnlyList< \fBValidationFailure\fP > failures)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IReadOnlyList< string > \fBPosition\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBCode\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBDescription\fP\fC [get]\fP"
.br
.ti -1c
.RI "IReadOnlyList< \fBValidationFailure\fP > \fBFailures\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file QueryError\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FaunaDB\&.Errors\&.QueryError\&.QueryError (IReadOnlyList< string > position, string code, string description, IReadOnlyList< \fBValidationFailure\fP > failures)"

.PP
Definition at line 17 of file QueryError\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string FaunaDB\&.Errors\&.QueryError\&.Code\fC [get]\fP"

.PP
Definition at line 10 of file QueryError\&.cs\&.
.SS "string FaunaDB\&.Errors\&.QueryError\&.Description\fC [get]\fP"

.PP
Definition at line 12 of file QueryError\&.cs\&.
.SS "IReadOnlyList<\fBValidationFailure\fP> FaunaDB\&.Errors\&.QueryError\&.Failures\fC [get]\fP"

.PP
Definition at line 14 of file QueryError\&.cs\&.
.SS "IReadOnlyList<string> FaunaDB\&.Errors\&.QueryError\&.Position\fC [get]\fP"

.PP
Definition at line 8 of file QueryError\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
