.TH "FaunaDB.Errors.ValidationFailure" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Errors.ValidationFailure
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValidationFailure\fP (IReadOnlyList< string > field, string code, string description)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IReadOnlyList< string > \fBField\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBCode\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBDescription\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file ValidationFailure\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FaunaDB\&.Errors\&.ValidationFailure\&.ValidationFailure (IReadOnlyList< string > field, string code, string description)"

.PP
Definition at line 15 of file ValidationFailure\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string FaunaDB\&.Errors\&.ValidationFailure\&.Code\fC [get]\fP"

.PP
Definition at line 10 of file ValidationFailure\&.cs\&.
.SS "string FaunaDB\&.Errors\&.ValidationFailure\&.Description\fC [get]\fP"

.PP
Definition at line 12 of file ValidationFailure\&.cs\&.
.SS "IReadOnlyList<string> FaunaDB\&.Errors\&.ValidationFailure\&.Field\fC [get]\fP"

.PP
Definition at line 8 of file ValidationFailure\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
