.TH "FaunaDB.Errors.UnavailableError" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Errors.UnavailableError \- HTTP 503 error\&. An exception thrown if a \fBFaunaDB\fP host is unavailable for any reason\&. For example, if the client cannot connect to the host, or if the host does not respond\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFaunaDB\&.Errors\&.FaunaException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
HTTP 503 error\&. An exception thrown if a \fBFaunaDB\fP host is unavailable for any reason\&. For example, if the client cannot connect to the host, or if the host does not respond\&. 

HTTP 503 error\&.
.PP
Definition at line 97 of file FaunaException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
