.TH "FaunaDB.Types.QueryV" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Types.QueryV \- Represents a query value in the \fBFaunaDB\fP query language\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ScalarValue< IReadOnlyDictionary< string, Expr >>\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBEquals\fP (\fBExpr\fP v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a query value in the \fBFaunaDB\fP query language\&. 

See \fBFaunaDB\fP Special \fBTypes\fP
.PP
\&. 
.PP
Definition at line 14 of file QueryV\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool FaunaDB\&.Types\&.QueryV\&.Equals (\fBExpr\fP v)"

.PP
Definition at line 27 of file QueryV\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
