.TH "FaunaDB.Client.LastSeen" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Client.LastSeen
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetTxn\fP (long time)"
.br
.RI "Set the last seen transaction time to the given time, if time is greater than the previously-seen time\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "long? \fBTxn\fP\fC [get]\fP"
.br
.RI "Returns the last seen transaction time, if any\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file LastSeen\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void FaunaDB\&.Client\&.LastSeen\&.SetTxn (long time)"

.PP
Set the last seen transaction time to the given time, if time is greater than the previously-seen time\&. 
.PP
Definition at line 35 of file LastSeen\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "long? FaunaDB\&.Client\&.LastSeen\&.Txn\fC [get]\fP"

.PP
Returns the last seen transaction time, if any\&. 
.PP
Definition at line 17 of file LastSeen\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
