.TH "FaunaDB.Client.Utils.CheckLatestVersion" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Client.Utils.CheckLatestVersion
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static async Task \fBGetVersionAsync\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static bool \fBAlreadyChecked\fP = false\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file CheckLatestVersion\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static async Task FaunaDB\&.Client\&.Utils\&.CheckLatestVersion\&.GetVersionAsync ()\fC [static]\fP"

.PP
Definition at line 18 of file CheckLatestVersion\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool FaunaDB\&.Client\&.Utils\&.CheckLatestVersion\&.AlreadyChecked = false\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 16 of file CheckLatestVersion\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
