.TH "FaunaDB.Types.RefID" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Types.RefID
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRefID\fP (string id, \fBRefV\fP collection, \fBRefV\fP database)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBId\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBRefV\fP \fBCollection\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBRefV\fP \fBDatabase\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file RefV\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FaunaDB\&.Types\&.RefID\&.RefID (string id, \fBRefV\fP collection, \fBRefV\fP database)"

.PP
Definition at line 14 of file RefV\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBRefV\fP FaunaDB\&.Types\&.RefID\&.Collection\fC [get]\fP"

.PP
Definition at line 10 of file RefV\&.cs\&.
.SS "\fBRefV\fP FaunaDB\&.Types\&.RefID\&.Database\fC [get]\fP"

.PP
Definition at line 12 of file RefV\&.cs\&.
.SS "string FaunaDB\&.Types\&.RefID\&.Id\fC [get]\fP"

.PP
Definition at line 8 of file RefV\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
