.TH "FaunaDB.Client.EventField" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Client.EventField
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBEventField\fP \fBDocumentField\fP => new \fBEventField\fP('document')"
.br
.ti -1c
.RI "static \fBEventField\fP \fBPrevField\fP => new \fBEventField\fP('prev')"
.br
.ti -1c
.RI "static \fBEventField\fP \fBDiffField\fP => new \fBEventField\fP('diff')"
.br
.ti -1c
.RI "static \fBEventField\fP \fBActionField\fP => new \fBEventField\fP('action')"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBValue\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file EventField\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBEventField\fP FaunaDB\&.Client\&.EventField\&.ActionField => new \fBEventField\fP('action')\fC [static]\fP"

.PP
Definition at line 18 of file EventField\&.cs\&.
.SS "\fBEventField\fP FaunaDB\&.Client\&.EventField\&.DiffField => new \fBEventField\fP('diff')\fC [static]\fP"

.PP
Definition at line 16 of file EventField\&.cs\&.
.SS "\fBEventField\fP FaunaDB\&.Client\&.EventField\&.DocumentField => new \fBEventField\fP('document')\fC [static]\fP"

.PP
Definition at line 12 of file EventField\&.cs\&.
.SS "\fBEventField\fP FaunaDB\&.Client\&.EventField\&.PrevField => new \fBEventField\fP('prev')\fC [static]\fP"

.PP
Definition at line 14 of file EventField\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string FaunaDB\&.Client\&.EventField\&.Value\fC [get]\fP"

.PP
Definition at line 10 of file EventField\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
