.TH "FaunaDB.Types.BytesV" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Types.BytesV \- A \fBFaunaDB\fP bytes type\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFaunaDB\&.Types\&.ScalarValue< byte[]>\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBEquals\fP (\fBExpr\fP v)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBBytesV\fP \fBOf\fP (string base64)"
.br
.ti -1c
.RI "static \fBBytesV\fP \fBOf\fP (params byte[] value)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override int \fBHashCode\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBFaunaDB\fP bytes type\&. 

See \fBFaunaDB\fP Special \fBTypes\fP
.PP
\&. 
.PP
Definition at line 15 of file BytesV\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool FaunaDB\&.Types\&.BytesV\&.Equals (\fBExpr\fP v)"

.PP
Definition at line 35 of file BytesV\&.cs\&.
.SS "override int FaunaDB\&.Types\&.BytesV\&.HashCode ()\fC [protected]\fP"

.SS "static \fBBytesV\fP FaunaDB\&.Types\&.BytesV\&.Of (params byte[] value)\fC [static]\fP"

.SS "static \fBBytesV\fP FaunaDB\&.Types\&.BytesV\&.Of (string base64)\fC [static]\fP"

.SS "override string FaunaDB\&.Types\&.BytesV\&.ToString ()"

.PP
Definition at line 49 of file BytesV\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
