.TH "FaunaDB.Types.BooleanV" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Types.BooleanV \- Represents a Boolean value in the \fBFaunaDB\fP query language\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFaunaDB\&.Types\&.ScalarValue< bool >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBBooleanV\fP \fBOf\fP (bool b)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBBooleanV\fP \fBTrue\fP = new \fBBooleanV\fP(true)"
.br
.ti -1c
.RI "static readonly \fBBooleanV\fP \fBFalse\fP = new \fBBooleanV\fP(false)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Represents a Boolean value in the \fBFaunaDB\fP query language\&. 


.PP
Definition at line 46 of file ScalarValue\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBBooleanV\fP FaunaDB\&.Types\&.BooleanV\&.Of (bool b)\fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "readonly \fBBooleanV\fP FaunaDB\&.Types\&.BooleanV\&.False = new \fBBooleanV\fP(false)\fC [static]\fP"

.PP
Definition at line 54 of file ScalarValue\&.cs\&.
.SS "readonly \fBBooleanV\fP FaunaDB\&.Types\&.BooleanV\&.True = new \fBBooleanV\fP(true)\fC [static]\fP"

.PP
Definition at line 53 of file ScalarValue\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
