.TH "FaunaDB.Errors.NotFound" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Errors.NotFound \- HTTP 404 error\&. An exception thrown if a HTTP 404 (Not Found) is returned from \fBFaunaDB\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFaunaDB\&.Errors\&.FaunaException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNotFound\fP (\fBQueryErrorResponse\fP response)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
HTTP 404 error\&. An exception thrown if a HTTP 404 (Not Found) is returned from \fBFaunaDB\fP\&. 

HTTP 404 error\&.
.PP
Definition at line 73 of file FaunaException\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FaunaDB\&.Errors\&.NotFound\&.NotFound (\fBQueryErrorResponse\fP response)"

.PP
Definition at line 75 of file FaunaException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
