.TH "FaunaDB.Query" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Query
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExpr\fP"
.br
.RI "A query language expression\&. Constructors for this class are at the \fBLanguage\fP class\&. "
.ti -1c
.RI "class \fBExprJsonConverter\fP"
.br
.ti -1c
.RI "struct \fBLanguage\fP"
.br
.RI "Methods modeling the \fBFaunaDB\fP query language\&. This class is intended to be statically imported into your code: "
.ti -1c
.RI "class \fBPageHelper\fP"
.br
.ti -1c
.RI "class \fBUnescapedArray\fP"
.br
.ti -1c
.RI "class \fBUnescapedObject\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
