.TH "FaunaDB.Types.NamingStrategy" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Types.NamingStrategy \- Naming strategy for \fBValue\fP encoder/decoder\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBFaunaDB\&.Types\&.CamelCaseNamingStrategy\fP, and \fBFaunaDB\&.Types\&.DefaultNamingStrategy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract string \fBResolvePropertyName\fP (string name)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBNamingStrategy\fP \fBDefault\fP = new \fBDefaultNamingStrategy\fP()\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Naming strategy for \fBValue\fP encoder/decoder\&. 


.PP
Definition at line 8 of file NamingStrategy\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract string FaunaDB\&.Types\&.NamingStrategy\&.ResolvePropertyName (string name)\fC [pure virtual]\fP"

.PP
Implemented in \fBFaunaDB\&.Types\&.CamelCaseNamingStrategy\fP, and \fBFaunaDB\&.Types\&.DefaultNamingStrategy\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBNamingStrategy\fP FaunaDB\&.Types\&.NamingStrategy\&.Default = new \fBDefaultNamingStrategy\fP()\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 10 of file NamingStrategy\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
