.TH "FaunaDB.Errors.BadRequest" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Errors.BadRequest \- HTTP 400 error\&. An exception thrown if \fBFaunaDB\fP cannot evaluate a query\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFaunaDB\&.Errors\&.FaunaException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
HTTP 400 error\&. An exception thrown if \fBFaunaDB\fP cannot evaluate a query\&. 

HTTP 400 error\&.
.PP
Definition at line 40 of file FaunaException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
