.TH "FaunaDB.Types.LongV" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Types.LongV \- Represents a Long value in the \fBFaunaDB\fP query language\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFaunaDB\&.Types\&.ScalarValue< long >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLongV\fP \fBOf\fP (long v)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Represents a Long value in the \fBFaunaDB\fP query language\&. 


.PP
Definition at line 71 of file ScalarValue\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBLongV\fP FaunaDB\&.Types\&.LongV\&.Of (long v)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
