.TH "FaunaDB.Errors.InternalError" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Errors.InternalError \- HTTP 500 error\&. An exception thrown if a HTTP 500 (Internal Server Error) occurs when making a request to \fBFaunaDB\fP\&. Such errors represent an internal failure within the database\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFaunaDB\&.Errors\&.FaunaException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
HTTP 500 error\&. An exception thrown if a HTTP 500 (Internal Server Error) occurs when making a request to \fBFaunaDB\fP\&. Such errors represent an internal failure within the database\&. 

HTTP 500 error\&.
.PP
Definition at line 85 of file FaunaException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
