.TH "FaunaDB.Types.RefV" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Types.RefV \- A \fBFaunaDB\fP ref type\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFaunaDB\&.Types\&.ScalarValue< RefID >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRefV\fP (string id, \fBRefV\fP collection=null, \fBRefV\fP database=null)"
.br
.ti -1c
.RI "override bool \fBEquals\fP (\fBExpr\fP v)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRefV\fP \fBOf\fP (string id, \fBRefV\fP collection=null, \fBRefV\fP database=null)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override int \fBHashCode\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBId\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBRefV\fP \fBCollection\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBRefV\fP \fBDatabase\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBFaunaDB\fP ref type\&. 

See \fBFaunaDB\fP Special \fBTypes\fP
.PP
\&. 
.PP
Definition at line 28 of file RefV\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FaunaDB\&.Types\&.RefV\&.RefV (string id, \fBRefV\fP collection = \fCnull\fP, \fBRefV\fP database = \fCnull\fP)"

.PP
Definition at line 36 of file RefV\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool FaunaDB\&.Types\&.RefV\&.Equals (\fBExpr\fP v)"

.PP
Definition at line 53 of file RefV\&.cs\&.
.SS "override int FaunaDB\&.Types\&.RefV\&.HashCode ()\fC [protected]\fP"

.SS "static \fBRefV\fP FaunaDB\&.Types\&.RefV\&.Of (string id, \fBRefV\fP collection = \fCnull\fP, \fBRefV\fP database = \fCnull\fP)\fC [static]\fP"

.SS "override string FaunaDB\&.Types\&.RefV\&.ToString ()"

.PP
Definition at line 66 of file RefV\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBRefV\fP FaunaDB\&.Types\&.RefV\&.Collection\fC [get]\fP"

.PP
Definition at line 32 of file RefV\&.cs\&.
.SS "\fBRefV\fP FaunaDB\&.Types\&.RefV\&.Database\fC [get]\fP"

.PP
Definition at line 34 of file RefV\&.cs\&.
.SS "string FaunaDB\&.Types\&.RefV\&.Id\fC [get]\fP"

.PP
Definition at line 30 of file RefV\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
