.TH "FaunaDB.Errors.QueryErrorResponse" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Errors.QueryErrorResponse
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQueryErrorResponse\fP (int statusCode, IReadOnlyList< \fBQueryError\fP > errors)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBStatusCode\fP\fC [get]\fP"
.br
.ti -1c
.RI "IReadOnlyList< \fBQueryError\fP > \fBErrors\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file QueryErrorResponse\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FaunaDB\&.Errors\&.QueryErrorResponse\&.QueryErrorResponse (int statusCode, IReadOnlyList< \fBQueryError\fP > errors)"

.PP
Definition at line 11 of file QueryErrorResponse\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "IReadOnlyList<\fBQueryError\fP> FaunaDB\&.Errors\&.QueryErrorResponse\&.Errors\fC [get]\fP"

.PP
Definition at line 9 of file QueryErrorResponse\&.cs\&.
.SS "int FaunaDB\&.Errors\&.QueryErrorResponse\&.StatusCode\fC [get]\fP"

.PP
Definition at line 7 of file QueryErrorResponse\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
