.TH "FaunaDB.Types.SetRefV" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaunaDB.Types.SetRefV \- A \fBFaunaDB\fP set literal\&. See \fBFaunaDB\fP Special \fBTypes\fP 

.SH SYNOPSIS
.br
.PP
.PP
Inherits ScalarValue< IReadOnlyDictionary< string, Value >>\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSetRefV\fP \fBOf\fP (IReadOnlyDictionary< string, \fBValue\fP > value)"
.br
.ti -1c
.RI "override bool \fBEquals\fP (\fBExpr\fP v)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBFaunaDB\fP set literal\&. See \fBFaunaDB\fP Special \fBTypes\fP


.PP
Definition at line 97 of file ScalarValue\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool FaunaDB\&.Types\&.SetRefV\&.Equals (\fBExpr\fP v)"

.PP
Definition at line 115 of file ScalarValue\&.cs\&.
.SS "override int FaunaDB\&.Types\&.SetRefV\&.GetHashCode ()"

.SS "\fBSetRefV\fP FaunaDB\&.Types\&.SetRefV\&.Of (IReadOnlyDictionary< string, \fBValue\fP > value)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
