.TH "/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Types/NamingStrategy.cs" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Types/NamingStrategy.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.NamingStrategy\fP"
.br
.RI "Naming strategy for \fBValue\fP encoder/decoder\&. "
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.DefaultNamingStrategy\fP"
.br
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.CamelCaseNamingStrategy\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFaunaDB\fP"
.br
.ti -1c
.RI "namespace \fBFaunaDB\&.Types\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
