.TH "/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Types/Option.cs" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Types/Option.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBFaunaDB\&.Types\&.IOption< T >\fP"
.br
.RI "Represents an optional value\&. "
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.Some< T >\fP"
.br
.ti -1c
.RI "interface \fBFaunaDB\&.Types\&.INone\fP"
.br
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.None< T >\fP"
.br
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.Option\fP"
.br
.RI "Represents an optional value\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFaunaDB\fP"
.br
.ti -1c
.RI "namespace \fBFaunaDB\&.Types\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
