.TH "/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Errors/QueryError.cs" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Errors/QueryError.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFaunaDB\&.Errors\&.QueryError\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFaunaDB\fP"
.br
.ti -1c
.RI "namespace \fBFaunaDB\&.Errors\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
