.TH "/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Types/ScalarValue.cs" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Types/ScalarValue.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.ScalarValue< TWrapped >\fP"
.br
.RI "Represents a scalar value at the \fBFaunaDB\fP query language\&. "
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.BooleanV\fP"
.br
.RI "Represents a Boolean value in the \fBFaunaDB\fP query language\&. "
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.DoubleV\fP"
.br
.RI "Represents a Double value in the \fBFaunaDB\fP query language\&. "
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.LongV\fP"
.br
.RI "Represents a Long value in the \fBFaunaDB\fP query language\&. "
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.StringV\fP"
.br
.RI "Represents a String value in the \fBFaunaDB\fP query language\&. "
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.SetRefV\fP"
.br
.RI "A \fBFaunaDB\fP set literal\&. See \fBFaunaDB\fP Special \fBTypes\fP"
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.ExprV\fP"
.br
.RI "A \fBFaunaDB\fP Expression wrapped as a \fBValue\fP "
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.TimeV\fP"
.br
.RI "Represents a Timestamp value in the \fBFaunaDB\fP query language\&. "
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.DateV\fP"
.br
.RI "Represents a Date value in the \fBFaunaDB\fP query language\&. "
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.DateTimeUtil\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFaunaDB\fP"
.br
.ti -1c
.RI "namespace \fBFaunaDB\&.Types\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
