.TH "/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Types/Value.cs" 3 "Thu Oct 7 2021" "Version 1.0" "Fauna csharp driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Work/fauna/faunadb-csharp/FaunaDB.Client/Types/Value.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFaunaDB\&.Types\&.Value\fP"
.br
.RI "Represents any scalar or non-scalar value in the \fBFaunaDB\fP query language\&. \fBFaunaDB\fP value types consist of all of the JSON value types, as well as the FaunaDB-specific types, \fBRefV\fP and \fBSetRefV\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFaunaDB\fP"
.br
.ti -1c
.RI "namespace \fBFaunaDB\&.Types\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna csharp driver from the source code\&.
