---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: notify
    type: slack-notification
    source:
      url: ((slack-webhook))

  - name: fauna-csharp-repository
    type: git
    icon: github
    source:
      uri: https://github.com/fauna/faunadb-csharp
      branch: v5
      
  - name: fauna-csharp-repository-docs
    type: git
    icon: github
    source:
      uri: git@github.com:fauna/faunadb-csharp.git
      branch: gh-pages
      private_key: ((github_repo_key))

jobs:
  - name: release
    serial: true
    public: false
    plan:
      - get: fauna-csharp-repository
      - get: fauna-csharp-repository-docs
      
      - task: integration-tests
        file: fauna-csharp-repository/concourse/tasks/integration-tests.yml
        privileged: true
        params:
          FAUNA_ROOT_KEY: ((fauna.secret))
          FAUNA_DOMAIN: ((fauna.domain))
          FAUNA_SCHEME: ((fauna.scheme))
          FAUNA_PORT: ((fauna.port))
          FAUNA_REPO_PASSWORD: ((gcr-key))
      
      - task: publish
        file: fauna-csharp-repository/concourse/tasks/publish.yml
        params:
          NUGET_API_KEY: ((nuget_api_key))
        on_success:
          put: notify
          params:
            text_file: slack-message/publish

      - task: publish-docs
        file: fauna-csharp-repository/concourse/tasks/publish-docs.yml

      - put: fauna-csharp-repository-docs
        params:
          repository: fauna-csharp-repository-updated-docs
