---
resources:
  - name: fauna-csharp-repository
    type: git
    icon: github
    source:
      uri: https://github.com/fauna/faunadb-csharp
      branch: main

jobs:
  - name: release
    serial: true
    public: false
    plan:
      - get: fauna-csharp-repository

      - task: integration-tests
        file: fauna-csharp-repository/concourse/tasks/integration-tests.yml
        privileged: true
        params:
          FAUNA_ROOT_KEY: ((fauna.secret))
          FAUNA_DOMAIN: ((fauna.domain))
          FAUNA_SCHEME: ((fauna.scheme))
          FAUNA_PORT: ((fauna.port))
          FAUNA_REPO_PASSWORD: ((gcr-key))
      
      # - task: publish
        # file: fauna-csharp-repository/concourse/tasks/publish.yml
        # params:
          # NUGET_API_KEY: ((nuget_api_key))
