---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: shared-concourse-dind
    aws_access_key_id: ((prod-images-aws-access-key-id))
    aws_secret_access_key: ((prod-images-aws-secret-key))
    aws_region: us-east-2

params:
  FAUNA_ROOT_KEY:
  FAUNA_DOMAIN:
  FAUNA_SCHEME:
  FAUNA_PORT:
  FAUNA_REPO_PASSWORD:

inputs:
  - name: fauna-csharp-repository

run:
  path: entrypoint.sh
  args:
    - bash
    - -ceu
    - |
      docker login -u _json_key -p "$FAUNA_REPO_PASSWORD" https://gcr.io > /dev/null 2>&1
      # start containers
      docker-compose -f fauna-csharp-repository/concourse/tasks/integration.yml run tests-net5
      docker-compose -f fauna-csharp-repository/concourse/tasks/integration.yml run tests-netcore
      # stop and remove containers
      docker-compose -f fauna-csharp-repository/concourse/tasks/integration.yml down
      # remove volumes
      docker volume rm $(docker volume ls -q)
      docker logout
