version: "3.3"

services:
  faunadb:
    image: gcr.io/faunadb-cloud/faunadb/core/nightly:latest
    container_name: faunadb
    healthcheck:
      test: ["CMD", "curl" ,"http://faunadb:8443/ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  tests-net5:
    environment:
      - FAUNA_ROOT_KEY
      - FAUNA_DOMAIN
      - FAUNA_SCHEME
      - FAUNA_PORT
    image: mcr.microsoft.com/dotnet/sdk:5.0-alpine
    container_name: mytests-net5
    depends_on:
      - faunadb
    volumes:
      - "../../:/tmp/app"
    working_dir: "/tmp/app"
    command:
      - concourse/scripts/integration-tests-net5.sh

  tests-netcore:
    environment:
      - FAUNA_ROOT_KEY
      - FAUNA_DOMAIN
      - FAUNA_SCHEME
      - FAUNA_PORT
    image: mcr.microsoft.com/dotnet/sdk:3.1-alpine
    container_name: mytests-netcore
    depends_on:
      - faunadb
    volumes:
      - "../../:/tmp/app"
    working_dir: "/tmp/app"
    command:
      - concourse/scripts/integration-tests-netcore.sh
