---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: mcr.microsoft.com/dotnet/sdk
    tag: 5.0-alpine

params:
  NUGET_API_KEY:

inputs:
  - name: fauna-csharp-repository

outputs:
  - name: slack-message

run:
  path: ./fauna-csharp-repository/concourse/scripts/publish.sh
