using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using FaunaDB.Client.Utils;
using FaunaDB.Collections;
using FaunaDB.Errors;
using FaunaDB.Query;
using FaunaDB.Types;
using Newtonsoft.Json;

namespace FaunaDB.Client
{
    /// <summary>
    /// C# native client for FaunaDB.
    /// <para>Queries are constructed by using static helpers in <see cref="Language"/> package.</para>
    /// </summary>
    /// <example>
    /// <code language="cs">
    /// var client = new FaunaClient(secret: "someAuthToken");
    /// client.Query(Get(Ref("some/ref")));
    /// </code>
    /// </example>
    public class FaunaClient
    {
        private readonly IClientIO clientIO;

        /// <summary>
        /// Constructs a new instance of <see cref="FaunaClient"/> with the specified arguments.
        /// </summary>
        /// <param name="secret">Auth token for the FaunaDB server.</param>
        /// <param name="endpoint">URL for the FaunaDB server. Defaults to "https://db.fauna.com:443"</param>
        /// <param name="queryTimeout">Timeout for I/O operations. Defaults to 1 minute.</param>
        /// <param name="httpVersion">Version of http. Default value is HttpVersion.Version11, is you use .net core 3.0 and above you can enable http/2 support by passing HttpVersion.Version20</param>
        /// <param name="checkNewVersion">Check new NuGet package driver version. Default value is true (Check new version).</param>
        public FaunaClient(
            string secret,
            string endpoint = "https://db.fauna.com:443",
            TimeSpan? queryTimeout = null,
            HttpClient httpClient = null,
            Version httpVersion = null,
            bool checkNewVersion = true,
            IReadOnlyDictionary<string, string> customHeaders = null)
            : this(CreateClient(secret, endpoint, queryTimeout, httpClient, httpVersion, checkNewVersion, customHeaders))
        { }

        /// <summary>
        /// Constructs a new instance of <see cref="FaunaClient"/> with the specified <see cref="IClientIO"/>.
        /// </summary>
        public FaunaClient(IClientIO clientIO)
        {
            clientIO.AssertNotNull(nameof(clientIO));
            this.clientIO = clientIO;
        }

        /// <summary>
        /// Creates a new <see cref="FaunaClient"/> with the user secret provided. Queries submitted to a session client will be
        /// authenticated with the secret provided. A session client shares its parent's internal resources.
        /// </summary>
        /// <param name="secret">Auth token for the FaunaDB server.</param>
        public FaunaClient NewSessionClient(string secret) =>
            new FaunaClient(clientIO.NewSessionClient(secret));

        /// <summary>
        /// Issues a Query to FaunaDB.
        /// <para>
        /// Queries are modeled through the FaunaDB query language, represented by the helper functions in the <see cref="Language"/> class.
        /// </para>
        /// <para>
        /// Responses are modeled as a general response tree. Each node is a <see cref="Value"/>, and
        /// can be coerced to structured types through various methods on that class.
        /// </para>
        /// </summary>
        /// <param name="expression">Expression generated by methods of <see cref="Language"/>.</param>
        /// <param name="queryTimeout">Timeout for that specific query (it will override the client timetout, if any).</param>
        public async Task<Value> Query(Expr expression, TimeSpan? queryTimeout = null) =>
            await Execute(HttpMethodKind.Post, string.Empty, expression, queryTimeout: queryTimeout).ConfigureAwait(false);

        /// <summary>
        /// Issues multiple queries to FaunaDB.
        /// <para>
        /// These queries are sent to FaunaDB in a single request, and are evaluated. The list of response nodes is returned
        /// in the same order as the issued queries.
        /// </para>
        /// <para>
        /// See <see cref="Query(Expr)"/> for more information on the individual queries.
        /// </para>
        /// </summary>
        /// <param name="expressions">the list of query expressions to be sent to FaunaDB.</param>
        /// <returns>a <see cref="Task"/> containing an ordered list of root response nodes.</returns>
        public async Task<Value[]> Query(params Expr[] expressions)
        {
            var response = await Query(new UnescapedArray(expressions)).ConfigureAwait(false);
            return response.Collect(Field.Root).ToArray();
        }

        /// <summary>
        /// Issues multiple queries to FaunaDB.
        /// <para>
        /// These queries are sent to FaunaDB in a single request, and are evaluated. The list of response nodes is returned
        /// in the same order as the issued queries.
        /// </para>
        /// <para>
        /// See <see cref="Query(Expr)"/> for more information on the individual queries.
        /// </para>
        /// </summary>
        /// <param name="queryTimeout">Timeout for that specific query (it will override the client queryTimeout, if any).</param>
        /// <param name="expressions">the list of query expressions to be sent to FaunaDB.</param>
        /// <returns>a <see cref="Task"/> containing an ordered list of root response nodes.</returns>
        public async Task<Value[]> Query(TimeSpan queryTimeout, params Expr[] expressions)
        {
            var response = await Query(new UnescapedArray(expressions), queryTimeout).ConfigureAwait(false);
            return response.Collect(Field.Root).ToArray();
        }

        /// <summary>
        /// Issues multiple queries to FaunaDB.
        /// <para>
        /// These queries are sent to FaunaDB in a single request, and are evaluated. The list of response nodes is returned
        /// in the same order as the issued queries.
        /// </para>
        /// <para>
        /// See <see cref="Query(Expr)"/> for more information on the individual queries.
        /// </para>
        /// </summary>
        /// <param name="expressions">the list of query expressions to be sent to FaunaDB.</param>
        /// <param name="queryTimeout">Timeout for that specific query (it will override the client queryTimeout, if any).</param>
        /// <returns>a <see cref="Task"/> containing an ordered list of root response nodes.</returns>
        public async Task<IEnumerable<Value>> Query(IEnumerable<Expr> expressions, TimeSpan? queryTimeout = null)
        {
            var response = await Query(new UnescapedArray(expressions.ToList()), queryTimeout).ConfigureAwait(false);
            return response.Collect(Field.Root);
        }

        /// <summary>
        /// Check service health.
        /// </summary>
        /// <param name="scope">Must be "node", "local", "global", or "all". Defaults to "global"</param>
        /// <param name="timeout">Time to wait for the ping to succeed, in milliseconds.</param>
        /// <returns>a <see cref="Task"/> with the message representing the result operation</returns>
        public async Task<string> Ping(string scope = null, int? timeout = null) =>
            (string)await Execute(HttpMethodKind.Get, "ping", query: ImmutableDictionary.Of("scope", scope, "timeout", timeout?.ToString())).ConfigureAwait(false);

        private async Task<Value> Execute(HttpMethodKind action, string path, Expr data = null, IReadOnlyDictionary<string, string> query = null, TimeSpan? queryTimeout = null)
        {
            var dataString = data == null ? null : JsonConvert.SerializeObject(data, Formatting.None);
            var responseHttp = await clientIO.DoRequest(action, path, dataString, query, queryTimeout).ConfigureAwait(false);

            RaiseForStatusCode(responseHttp);

            var responseContent = FromJson(responseHttp.ResponseContent);
            return responseContent["resource"];
        }

        public async Task<StreamingEventHandler> Stream(Expr data = null, IReadOnlyList<EventField> fields = null)
        {
            var dataString = data == null ? null : JsonConvert.SerializeObject(data, Formatting.None);
            var queryParams = fields != null
                ? ImmutableDictionary.Of("fields", string.Join(",", fields.Select(v => v.Value)))
                : null;
            var responseHttp = await clientIO.DoStreamingRequest(dataString, queryParams);

            RaiseForStatusCode(responseHttp);

            return new StreamingEventHandler(responseHttp.ResponseContent);
        }

        internal struct ErrorsWrapper
        {
            public IReadOnlyList<QueryError> Errors;
        }

        internal static void RaiseForStatusCode(RequestResult resultRequest)
        {
            var statusCode = resultRequest.StatusCode;

            if (statusCode >= 200 && statusCode < 300)
            {
                return;
            }

            var wrapper = JsonConvert.DeserializeObject<ErrorsWrapper>(resultRequest.ResponseContent);

            var response = new QueryErrorResponse(statusCode, wrapper.Errors);

            throw ExceptionResolver.Resolve(response, statusCode).FirstOrDefault();
        }

        internal static void RaiseForStatusCode(StreamingRequestResult resultRequest)
        {
            var statusCode = resultRequest.StatusCode;

            if (statusCode >= 200 && statusCode < 300)
            {
                return;
            }

            var wrapper = JsonConvert.DeserializeObject<ErrorsWrapper>(resultRequest.ErrorContent);

            var response = new QueryErrorResponse(statusCode, wrapper.Errors);
            throw ExceptionResolver.Resolve(response, statusCode).FirstOrDefault();
        }

        public static ObjectV FromJson(string json)
        {
            try
            {
                var settings = new JsonSerializerSettings { DateParseHandling = DateParseHandling.None };
                return JsonConvert.DeserializeObject<ObjectV>(json, settings);
            }
            catch (JsonReaderException ex)
            {
                throw new UnknownException($"Bad JSON: {ex}");
            }
        }

        private static IClientIO CreateClient(
            string secret,
            string endpoint,
            TimeSpan? queryTimeout = null,
            HttpClient httpClient = null,
            Version httpVersion = null,
            bool checkNewVersion = true,
            IReadOnlyDictionary<string, string> customHeaders = null)
        {
            secret.AssertNotNull(nameof(secret));
            endpoint.AssertNotNull(nameof(endpoint));

            if (checkNewVersion && !CheckLatestVersion.AlreadyChecked)
            {
                Task.Run(() => CheckLatestVersion.GetVersionAsync());
            }

            return DefaultClientIO.Builder()
                                  .SetSecret(secret)
                                  .SetEndpoint(new Uri(endpoint))
                                  .SetTimeout(queryTimeout)
                                  .SetClient(httpClient)
                                  .SetHttpVersion(httpVersion)
                                  .Build();
        }
    }
}
